### ISSUE TITLE
What does "none select for random" mean (options page)?

### ISSUE THREAD

**Issue by realpixelcode** [bluelockorg/Blue-Privacy-Extension#19]
Um, I really don't understand what this phrase is supposed to mean. 🤔 Or is this a common English term I don't understand as a foreigner? 😅 I mean: This phrase appears even though I've selected multiple search engines in the options page...

I need this info in order to translate it into German 🤪

**Comment by aapl-yumi** [comment]
This is supposed to mean, "if no search engine is selected by the user, the extension will randomly choose a search engine to redirect to". So, if none of the search engines are picked by user (shown in the image), the search engine that will be redirected to will be random.
![Screen Shot 2020-12-05 at 19 05 09](https://user-images.githubusercontent.com/36561306/101239669-ce0d5100-372c-11eb-87da-2019fd22b8dc.png)

I'm very sorry for making it very confusing. I should probably change it in English as well. Sorry, I do see why this could be a confusion.

Thank you for the call out!!　😄

**Comment by realpixelcode** [comment]
Ah, that makes sense. Thanks for the clarification. But why then does it appear even if I did select some search engines? 🤔 Or is the string not supposed to disappear at all? I'm standing on the cable right now, as we Germans say 😅


![BluePrivacyExtension none for random](https://user-images.githubusercontent.com/52963327/101240865-de500c80-36e9-11eb-9882-a443eaec0209.png)

**Comment by aapl-yumi** [comment]
Oh yeah! It’s supposed to be showing all the time. I think I should change this as it is very confusing. I’ll use the same string so don’t worry about re-translating. Thank you!

**Comment by aapl-yumi** [comment]
I will close this as I changed it to "none for random", which hopefully is easier to understand. Thank you for pointing this out!
