### ISSUE TITLE
Suggestions for additional search engines

### ISSUE THREAD

**Issue by realpixelcode** [bluelockorg/Blue-Privacy-Extension#3]
- [Metager](https://metager.org)
- [SearX](https://github.com/searx/searx); some of the [instances](https://searx.space) are even available via onion addresses (What about including them for Tor users?)

**Comment by aapl-yumi** [comment]
That's a great idea. I will try to implement those ideas in the upcoming updates.

**Comment by aapl-yumi** [comment]
I was able to implement metager. However, for SearX, there are so many instances. Do you have any specific one we should use?

**Comment by realpixelcode** [comment]
I think you need Searx instances that are run reliably so here are some ones from respectable organizations:

- [PrivacyTools.io](https://privacytools.io): https://search.privacytools.io/searx
- [/e/](https://e.foundation): https://spot.ecloud.global
- [Disroot](https://disroot.org): https://search.disroot.org

Btw: I've found [Swisscows](https://swisscows.com), another privacy-friendly search engine.

**Comment by aapl-yumi** [comment]
Thank you. I will implement these ASAP.

**Comment by aapl-yumi** [comment]
I have been able to implement these. I will publish these in the next update, 0.0.9. Thank you a lot for these suggestions!

**Comment by aapl-yumi** [comment]
Should I close this issue or should I keep it open for more suggestions for search engines? @realpixelcode 

Btw, the new update, [0.0.9](https://github.com/bluelockorg/Blue-Privacy-Extension/commit/7d0c3c3e6e95f3ac6c5dc67bb4f1f60fa0331b58), has been published. Should be coming soon on the Chrome and Firefox's stores.

**Comment by realpixelcode** [comment]
Well, keeping it opened may help you collect suggestions from may others. Then you can tell everyone "If you have recommendations regarding search engines please refer to issue #3 and check that it's not a duplicate". So I'd keep it ☺️

**Comment by aapl-yumi** [comment]
Thanks for the suggestion! I will do so.

**Comment by aapl-yumi** [comment]
@realpixelcode As Discussions has came to GitHub, I will close this and use [this](https://github.com/bluelockorg/Blue-Privacy-Extension/discussions/21) as a place to suggest search engines!
